### ISSUE TITLE
Formatting issues with german (mobile) numbers

### ISSUE THREAD

**Issue by itinance** [catamphetamine/libphonenumber-js#127]
I've found out that - against to googles phone number parser - formatting issues exists for german phone numbers (especially the ones for mobile), when the optional zero is passed (which is well common used in germany)

Has someone any ideas?

**Code:**
`console.log(2, format({ country: 'DE', phone: '+49(0)15123020522' }, 'International'))`

**Received:**
+49 015123020522

**Expected:**
+49 1512 3020522

[Google phone-number-parser:](https://libphonenumber.appspot.com/phonenumberparser?number=%2B49(0)15123020522&country=DE)
https://libphonenumber.appspot.com/phonenumberparser?number=%2B49(0)15123020522&country=DE

**Comment by catamphetamine** [comment]
The link for the Google demo you provided outputs the same formatting:
`+49(0)15123020522`

**Comment by malakutsko** [comment]
Since `format` function expects parsed phone number, I would say, that the problem is in `parse` function:

**Code:**
```
parse('+49(0)15123020522', 'DE')
```
**Actual result:**
```
{}
```
**Expected result:**
```
{country: "DE", phone: "15123020522"}
```
Version: libphonenumber-js@1.1.3

To make this work I remove `(0)` from the string before parsing it, not sure it's right thing to do generally though. But on google demo looks like `libphonenumber` parses it as expected.

**Comment by catamphetamine** [comment]
Yes, I didn't mention it in the "differences" list.
The thing is national prefix can not be present in international phones:
http://ucken.blogspot.ru/2016/03/trunk-prefixes-in-skype4b.html
I previously chose to remove such loose parsing feature from `parse()`.

Since this feature has been requested multiple times I've added it back to this library.
It now supports parsing such invalid international phone numbers.
Install the latest version `libphonenumber-js@1.1.4`.
