### ISSUE TITLE
Allow parse and format functions to accept numbers instead of strings

### ISSUE THREAD

**Issue by jaufgang** [catamphetamine/libphonenumber-js#142]
We recently ran into an issue where the parse and format functions were not working and it took us a long time to figure out that it was because the phone numbers we were feeding to the functions were being retrieved from a db as number types rather than strings.  Once we figured it out it was pretty easy to remedy by calling `.toString()` before passing the values to the functions.

I would like to suggest adding support for phone numbers  passed in as number types so that other users don't experience this problem.  simply checking the type of input and calling `.toString()` would solve the problem.

**Comment by catamphetamine** [comment]
I see.
Indeed, storing telephone numbers in numerical form can seem lame at first but considering an 8-byte bigint has capacity for representing up to 18 digits (and javascript Number has capacity for representing up to 15 digits) it's actually not that bad of an idea due to space savings.
Not sure if there are phone numbers longer than 15 digits though.
Ok, I've added that feature in the latest release.

**Comment by catamphetamine** [comment]
FYI: I'm gonna be removing this feature in version `1.0.2` because it's an erroneous approach.
More info in the end of the document.
https://github.com/googlei18n/libphonenumber/blob/master/FALSEHOODS.md
