### ISSUE TITLE
URGENT

### ISSUE THREAD

**Issue by nesbtesh** [catamphetamine/libphonenumber-js#160]
A lot of websites that are using your plugin, have my number as the default number for the country Panama: https://www.allcoin.com/. I am receiving hundreds of calls from people thinking they are calling the website.

my number is +507-6002-2345

Can you please change the default number to another number, that is not my number, thanks

**Comment by catamphetamine** [comment]
Ha ha, that's funny.
That's why i'm not using "example values" as "placeholders" in forms — they're just too confusing for people who mistakently take them for the actual real pre-filled values.
Speaking of this exact library the examples are stored in this file:
https://github.com/catamphetamine/libphonenumber-js/blob/master/examples.mobile.json
And there's no `60022345` in that file.
So I guess you're barking the wrong tree here.

**Comment by catamphetamine** [comment]
Screenshot for history

![image](https://user-images.githubusercontent.com/477167/34729782-ab939006-f56e-11e7-9038-d8f16ce0ebbd.png)

**Comment by catamphetamine** [comment]
And yeah, they're definitely not using my React component here, they're using another one:
https://intl-tel-input.com/

**Comment by nesbtesh** [comment]
Sorry i meant +507-6001-2345 it was a typo

**Comment by Henri73** [comment]
Nesbtesh,

More importantly, is this still your number? I've been receiving a number of calls from this Panama number to an Irish mobile in the past fortnight.
Most recently at 9:57am GMT and a few minutes after a scam text purporting to be from the Irish Revenue Commissioners.

Can you explain why your number is ringing +353.85.7050xxx frequently??

**Comment by Henri73** [comment]
@nesbtesh, I will contact you through Twitter as I've located you there.
Perhaps you are interested in purchasing domain names.
