### ISSUE TITLE
Customizing metadata

### ISSUE THREAD

**Issue by gety9** [catamphetamine/libphonenumber-js#162]
Not an issue but a question,

Is it possible to customize/minimize metadata so it will contain getPhoneCode data for all countries and asYouType data for 4 countries?

**Comment by catamphetamine** [comment]
Not clear what you mean

**Comment by gety9** [comment]
The default metadata used is metadata.min.json — 70 KiloBytes.

Is there a way i can make needed file smaller, if only 2 things i would like to use from the library are:

asYouType for 4 countries (that's countries who are 90% of our customers and i want to make phone number for them UX friendly)

getPhoneCode for all countries (we populate country code for them, basically if they select AU, than we auto write +61)

**Comment by catamphetamine** [comment]
I see.
A solution would be to generate metadata for the 90% customers' countries and then manually inject all phone codes from `metadata.min.json` to to that metadata.
https://unpkg.com/libphonenumber-js@0.4.49/metadata.min.json
That could be done via a simple Node.js script.

**Comment by gety9** [comment]
Thank you so much!

**Comment by catamphetamine** [comment]
You'll have to write your own `getPhoneCode()` because the default one won't work as it requires country metadata. Or you could stub country metadata with just the code for other countries. So, if you won't be using the default `getPhoneCode()` function then just generate metadata for the 90% users' countries and then write your own `getPhoneCode()` function copy-pasting the phone codes data from `metadata.min.json` provided above.

**Comment by gety9** [comment]
Nikolay, thank you for taking time and explaining me all this!
I really appreciate!
