### ISSUE TITLE
Changelog out of date

### ISSUE THREAD

**Issue by nobitagit** [catamphetamine/libphonenumber-js#321]
Changelog seems to be stuck on [v 1.7.6](https://github.com/catamphetamine/libphonenumber-js/blob/master/CHANGELOG.md#176--11012019), while latest version of this lib is 1.7.18.

It's very useful when upgrading to quickly skim through it so I think it's worth revamping this file now that it's not too far behind, what do you think?

**Comment by catamphetamine** [comment]
So somebody does read that file (as intended), I see.
Yeah, if you look at the commits those are mostly "Metadata update" and TypeScript definition pull requests, so there're usually no new features.
https://github.com/catamphetamine/libphonenumber-js/commits/master
Bug fixes usually aren't documented because whatever.
Usually only stuff that could cause migration gets into that file.
There hasn't been much development on this library this year and I guess it has reached it's final state or something like that.
