### ISSUE TITLE
isValidNumberForRegion() commented

### ISSUE THREAD

**Issue by drocsid** [catamphetamine/libphonenumber-js#322]
Hi,

I was wondering why I couldn't call `isValidNumberForRegion()`. It appears to be commented. Also I have read your concerns regarding it...

Then I used: `return phoneNumber.isValid() && phoneNumber.country === countrycode` as mentioned in the comments. If I use the `max` imports, should I expect the same behavior as  `isValidNumberForRegion()` from the google `libphonenumber`? Why not just provide it from the phoneNumber class?

**Comment by catamphetamine** [comment]
Hi.
If `isValidNumberForRegion()` was implemented then the code would be `return phoneNumber.isValid() && phoneNumber.country === countrycode`.
"Is valid number for region" literally means that the number "is valid" and that the region is the "region".
From how I see it, there's no need to add an alias for this case because it's just a legacy function name from `libphonenumber` and for a person coming not from `libphonenumber` it would be a bit of extra confusion.
But for a person coming from Google's library the absense of such function would be a bit of confusion.
Since this library's interface is not a 1:1 mirroring I guess we're leaving that function out for now.
