### ISSUE TITLE
Not really honest size comparison

### ISSUE THREAD

**Issue by grantila** [catamphetamine/libphonenumber-js#346]
Google's libphonenumber can be compiled to a lot smaller than 500k+. My version ([awesome-phonenumber](https://www.npmjs.com/package/awesome-phonenumber)) is:

```sh
$ yarn add awesome-phonenumber
$ du -hs node_modules
284K	node_modules
```

This library depends on `minimist` and `xml2js` which makes `libphonenumber-js` become pretty big:

```sh
$ yarn add libphonenumber-js
$ du -hs node_modules
7,1M	node_modules
```

So [awesome-phonenumber](https://www.npmjs.com/package/awesome-phonenumber) is **25x** smaller than this library.

**Comment by catamphetamine** [comment]
Hi.
Your comparison is not valid because `libphonenumber-js` doesn't bundle neither `minimist` nor `xml2js`. Those two dependencies are used in the "generate custom metadata" command-line utility supplied as part of this package. Perhaps that command-line utility could be presented by some separate `libphonenumber-js-cli` package but historically it's part of the `libphonenumber-js` package and it's not included in the bundle.
