### ISSUE TITLE
Why don't you create releases anymore?

### ISSUE THREAD

**Issue by jezzsantos** [catamphetamine/libphonenumber-js#348]
Your last release on github was 0.2.2.
We dont consume npm, we are using your library as raw JS files.

Are you at lease able to tag your repo every release? so that we can extract the JS files?

**Comment by catamphetamine** [comment]
Hello.
I'm not using GitHub releases.
The ones existing seem to be un-deletable.
They seem to have been created by accident.
People're using CDN files and those should be "UMD" aka "working in Node" though there've been reports of them demanding `window` or something.
Anyway, that's it.
Closing this issue because we're not providing GitHub releases.

**Comment by jezzsantos** [comment]
OK, fair enough.

The reason you have those releases, and cant delete them: github creates a release automatically for you when you tag a commit in the repo.

That's what I was asking you to do from now on.
Just simply add tag like `1.7.26` to the commit that represents your next release. Github then does the magic to create you a release. You don't have to do much else for that to occur.
I was then asking if you could go one extra step and add the raw JS and MAP files to the release container that github creates you, so that we consume those files directly.

**Comment by catamphetamine** [comment]
> That's what I was asking you to do from now on.

I don't see any value in maintaining "GitHub releases".
For me, npm is already enough, and CDN builds is something people kept asking so I added them too.
I definitely won't be doing any extra manual actions when releasing things, so unless it's fully automated and someone else sets it up then it won't be happening.
