### ISSUE TITLE
semver fails when it comes to pre-releases

### ISSUE THREAD

**Issue by Alan-Liang** [catamphetamine/libphonenumber-js#381]
## Steps to reproduce

1. Change the version in `package.json` from `1.7.44` to something like `1.7.44-build1`
1. `npm run metadata:generate`
1. `npm run test`

## Google's demo link

N/A

See also: https://github.com/substack/semver-compare/issues/1 .

**Comment by catamphetamine** [comment]
Hi.
Ok, seems like a `semver-compare` bug, but what are the observed result and expected result of running the steps you've described.
In other words, what's the exact issue you're having?

**Comment by Alan-Liang** [comment]
The exact issue is a test failure at 
That is caused by https://github.com/catamphetamine/libphonenumber-js/blob/master/source/metadata.js treating metadata as V3.

**Comment by catamphetamine** [comment]
@Alan-Liang All tests pass both on my machine and on Travis CI.

**Comment by Alan-Liang** [comment]
A reproduction log: https://gist.github.com/Alan-Liang/b3576f18607dc4dba0eb2d616ebc7e05

**Comment by catamphetamine** [comment]
@Alan-Liang 

> cat package.json | grep version  "version": "1.7.45-build1",

This library could potentially use alpha/beta releases but it doesn't.
So this issue isn't really an issue for this library.
If you want to maintain a fork with alpha/beta releases then you could fix that bug.
The code is in the source folder (`semver-compare` isn't installed as a dependency, it's copy-pasted in the source code folder).
So I won't be fixing this one because it's not an issue for me.

**Comment by catamphetamine** [comment]
@Alan-Liang A quick fix could be trimming everything after `-` in the `version`.
You can submit a pull request with a fix (and with some unit tests).

**Comment by catamphetamine** [comment]
Actually, I could do this quick fix myself.
Maybe in the evening.

**Comment by catamphetamine** [comment]
Published `libphonenumber-js@1.7.46`.
