### ISSUE TITLE
Wrong value for phone that's start from +1 8001 

### ISSUE THREAD

**Issue by VasylenkoStanislav** [catamphetamine/libphonenumber-js#412]
## Steps to reproduce
 parsePhoneNumberFromString('+18001646460');

## Observed result
This expression return country set to Dominicana 
countryCallingCode: "1"
nationalNumber: "8001646460"
number: "+18001646460"
country: "DO"

Expected result country: "US"

**Comment by catamphetamine** [comment]
You haven't provided a link to Google's demo
https://github.com/catamphetamine/libphonenumber-js#bug-reporting

**Comment by gtoroptsev** [comment]
I also encountered same issue, the solution is to use max metadata sets instead of min, you can read about it in docs
(tbh, at first I thought that "min" postfix in CDN's url is minified version of script):

[https://github.com/catamphetamine/libphonenumber-js#min-vs-max-vs-mobile-vs-core](https://github.com/catamphetamine/libphonenumber-js#min-vs-max-vs-mobile-vs-core)
